[package]
name = "osc52"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.1"  # msrv
resolver = "2"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
clap = { version = "4.5.48", features = ["derive"] }
